### ISSUE TITLE
谷歌云盘权限

### ISSUE THREAD

**Issue by akatinn** [jmpu/DeepfakeTextDetection#1]
您好，我想下载一下模型与数据集，谷歌云盘需要权限，申请后一直没消息，可以通过一下吗

**Comment by akatinn** [comment]
你好，我这边没有获得权限，是不方便分享模型与数据集吗

**Comment by jmpu** [comment]
hello, 我已经通过了最近所有的request，不知道为什么。要不您再google form apply一下？或者给我直接发邮件，把您的邮箱告诉我

**Comment by akatinn** [comment]
给您发邮件啦，如果没收到的话请提醒我再发一下。

**Comment by akatinn** [comment]
***@***.***，谢谢٩( 'ω' )و&nbsp;




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月1日(周一) 下午2:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jmpu/DeepfakeTextDetection] 谷歌云盘权限 (Issue #1)




 
hello, 我已经通过了最近所有的request，不知道为什么。要不您再google form apply一下？或者给我直接发邮件，把您的邮箱告诉我

**Comment by jmpu** [comment]
还是用google form apply一遍吧，我这里没有收到邮件。

**Comment by akatinn** [comment]
好像还是有点问题，麻烦您看能不能发这个邮箱吧，1300187375 at qq.com

**Comment by akatinn** [comment]
还有，能问一下您在BERT-defense里的finetuning中用的原始模型是什么吗？

**Comment by akatinn** [comment]
我用新的邮箱重新申请了一次，麻烦您通过申请共享一下，或者您直接发到这个邮箱也可以：huziyao@gmail.com

**Comment by maherr13** [comment]
Would you share the dataset and checkpoint with me? 
@akatinn @jmpu
