### ISSUE TITLE
Datasets are unavailable

### ISSUE THREAD

**Issue by ZackyWasTaken** [jmpu/DeepfakeTextDetection#2]
I cannot access the datasets, with the gdrive folder empty and the request form closed. I don't know if this is the right place to ask if an alternative is available. However, it'd help me immensely.

**Comment by SifatMd** [comment]
We are working on fixing the links. We will give an update asap.

**Comment by SifatMd** [comment]
The form is live now. The data and pre-trained models are also available now. Please check them. Apologies for the inconvenience.

**Comment by ZackyWasTaken** [comment]
Will do. Thanks for the quick effective work!
